### ISSUE TITLE
wish: document handling a param with multiple values

### ISSUE THREAD

**Issue by markstos** [flitto/express-param#14]
Most keys have  one value, but some have multiple values.

It would be helpful if it there was related documentation:
- How you declare if you expect one value or multiple values?
- What happens if you expect one value, but a second value is passed?

**Comment by dankang** [comment]
You mean... supporting array type?

**Comment by markstos** [comment]
Not just supporting (which might already be there), but documenting support.

**Comment by BumjuneKim** [comment]
@markstos 
I don't understand what you are talking about..
Especially.. multiple values.. What are multiple values?.. They mean array type?
Could you explain again with simple examples? They are helpful to understand

**Comment by markstos** [comment]
Example:

    /path/?key=value1&key=value2

**Comment by markstos** [comment]
People who are concerned about the [HTTP Parameter Pollution](https://www.owasp.org/index.php/Testing_for_HTTP_Parameter_pollution_(OTG-INPVAL-004)) security vulnerability will be interested to know how your middleware handles keys with multiple values so they can understand how it might help guard against this issue (or not).

**Comment by tiggerk** [comment]
@markstos Sorry to keep you waiting so long. Please check the update. #19 
I will consider array type that uses multiple values.
